// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu9aMGJ1MabXQgKg20EJYYhsFs4c-F04Q',
    appId: '1:567756244590:web:2a477ef8b12a0fcbaa087f',
    messagingSenderId: '567756244590',
    projectId: 'one-body-7f331',
    authDomain: 'one-body-7f331.firebaseapp.com',
    storageBucket: 'one-body-7f331.appspot.com',
    measurementId: 'G-WGZBV4S0DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuA8TFfsLMJR-8nUWqrcBYJ31Oo2LRuG0',
    appId: '1:567756244590:android:b8c223c1aa0a5f86aa087f',
    messagingSenderId: '567756244590',
    projectId: 'one-body-7f331',
    storageBucket: 'one-body-7f331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMDOpQ2RMIm00jfwwqDipPqas7pdtw184',
    appId: '1:567756244590:ios:faeed11bff5ebbadaa087f',
    messagingSenderId: '567756244590',
    projectId: 'one-body-7f331',
    storageBucket: 'one-body-7f331.appspot.com',
    iosClientId: '567756244590-nb0p1lueb23foqjegp4tb4agj2r19k5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneBody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMDOpQ2RMIm00jfwwqDipPqas7pdtw184',
    appId: '1:567756244590:ios:e74e67bbdde7aeedaa087f',
    messagingSenderId: '567756244590',
    projectId: 'one-body-7f331',
    storageBucket: 'one-body-7f331.appspot.com',
    iosClientId: '567756244590-s06us3914pss00kgfft60ftgt3gsutf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneBody.RunnerTests',
  );
}
